- debug:
    msg: "Jestem qkrowa"

- name: node free
  virt:
    command: list_vms

- name: templae
  debug:
    msg: "{{ lookup('template', 'vol_template.xml') }}"

#TODO ugly placeholder
- name: create qcow disk
  shell: virsh vol-create default <(echo '{{ lookup("template", "vol_template.xml") }}')
  args:
    executable: /bin/bash
    creates: "/var/lib/libvirt/images/{{ new_instance.value.name }}.qcow2"
  environment:
    LIBVIRT_DEFAULT_URI: "qemu:///system"
  #become: True
  #  virt:
  #    command: define
  #    xml: "{{ lookup('template', 'vol_template.xml') }}"
